<a href="https://colab.research.google.com/github/cawllol/Deep-learning/blob/master/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.keras.preprocessing.text import one_hot

In [0]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [0]:
# Vocabulary size
voc_size=10000

In [5]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5966, 1307, 6493, 2614], [5966, 1307, 6493, 7527], [5966, 3238, 6493, 9020], [6975, 6343, 5241, 7264, 6700], [6975, 6343, 5241, 7264, 5737], [9164, 5966, 481, 6493, 434], [5787, 6579, 9026, 7264]]


In [0]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5966 1307 6493 2614]
 [   0    0    0    0 5966 1307 6493 7527]
 [   0    0    0    0 5966 3238 6493 9020]
 [   0    0    0 6975 6343 5241 7264 6700]
 [   0    0    0 6975 6343 5241 7264 5737]
 [   0    0    0 9164 5966  481 6493  434]
 [   0    0    0    0 5787 6579 9026 7264]]


In [0]:
dim=10

In [0]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 3.59353311e-02  4.39067520e-02  3.24959792e-02 -4.30503152e-02
    1.33381747e-02  1.27814524e-02 -1.35960355e-02  1.05849393e-02
   -3.10707819e-02  7.69815594e-03]
  [ 3.59353311e-02  4.39067520e-02  3.24959792e-02 -4.30503152e-02
    1.33381747e-02  1.27814524e-02 -1.35960355e-02  1.05849393e-02
   -3.10707819e-02  7.69815594e-03]
  [ 3.59353311e-02  4.39067520e-02  3.24959792e-02 -4.30503152e-02
    1.33381747e-02  1.27814524e-02 -1.35960355e-02  1.05849393e-02
   -3.10707819e-02  7.69815594e-03]
  [ 3.59353311e-02  4.39067520e-02  3.24959792e-02 -4.30503152e-02
    1.33381747e-02  1.27814524e-02 -1.35960355e-02  1.05849393e-02
   -3.10707819e-02  7.69815594e-03]
  [ 1.29233040e-02 -2.71104276e-04  4.22314517e-02  9.12540033e-03
   -4.51164730e-02 -1.24353059e-02  4.39023413e-02  4.00954820e-02
    4.29261476e-04  1.09533072e-02]
  [ 4.59936373e-02 -4.71576229e-02 -7.38642365e-03  1.95495747e-02
   -6.03187084e-03 -4.44491282e-02  8.87882710e-03  3.55279185e-02
    1.79862417e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5966, 1307, 6493, 2614], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[ 3.5935331e-02  4.3906752e-02  3.2495979e-02 -4.3050315e-02
   1.3338175e-02  1.2781452e-02 -1.3596036e-02  1.0584939e-02
  -3.1070782e-02  7.6981559e-03]
 [ 3.5935331e-02  4.3906752e-02  3.2495979e-02 -4.3050315e-02
   1.3338175e-02  1.2781452e-02 -1.3596036e-02  1.0584939e-02
  -3.1070782e-02  7.6981559e-03]
 [ 3.5935331e-02  4.3906752e-02  3.2495979e-02 -4.3050315e-02
   1.3338175e-02  1.2781452e-02 -1.3596036e-02  1.0584939e-02
  -3.1070782e-02  7.6981559e-03]
 [ 3.5935331e-02  4.3906752e-02  3.2495979e-02 -4.3050315e-02
   1.3338175e-02  1.2781452e-02 -1.3596036e-02  1.0584939e-02
  -3.1070782e-02  7.6981559e-03]
 [ 1.2923304e-02 -2.7110428e-04  4.2231452e-02  9.1254003e-03
  -4.5116473e-02 -1.2435306e-02  4.3902341e-02  4.0095482e-02
   4.2926148e-04  1.0953307e-02]
 [ 4.5993637e-02 -4.7157623e-02 -7.3864236e-03  1.9549575e-02
  -6.0318708e-03 -4.4449128e-02  8.8788271e-03  3.5527918e-02
   1.7986242e-02  4.0700324e-03]
 [-2.7066935e-02  1.9121561e-02 -2.1605169e-02 -1.7293297e